Repository flag-camp-2020-t3/Spare4Fun-Server, pull requests merged in 2020-11, with the labels that each got.

#3 Create Authorities.java
  src/main/java/com/spare4fun/core/entity/Authorities.java
Labels: good first issue, help wanted

#7 Entity location
  src/main/java/com/spare4fun/core/entity/Location.java
Labels: good first issue, help wanted

#5 Create ItemCondition.java
  src/main/java/com/spare4fun/core/entity/ItemCondition.java
Labels: good first issue, help wanted

#6 Create Category.java
  src/main/java/com/spare4fun/core/entity/Category.java
Labels: good first issue, help wanted

#13 Entity Level-1 Dependency of Level-2
  src/main/java/com/spare4fun/core/entity/Authorities.java
  src/main/java/com/spare4fun/core/entity/Category.java
  src/main/java/com/spare4fun/core/entity/Item.java
  src/main/java/com/spare4fun/core/entity/ItemCondition.java
  src/main/java/com/spare4fun/core/entity/Location.java
  src/main/java/com/spare4fun/core/entity/User.java
  src/main/java/com/spare4fun/core/entity/UserInfo.java
Labels: help wanted

#14 Entity timeslot
  src/main/java/com/spare4fun/core/entity/TimeSlot.java
Labels: help wanted

#15 Entity payment order
  src/main/java/com/spare4fun/core/entity/PaymentOrder.java
Labels: help wanted

#16 Database V1.0 merge to master branch
  src/main/java/com/spare4fun/core/entity/Appointment.java
  src/main/java/com/spare4fun/core/entity/Authorities.java
  src/main/java/com/spare4fun/core/entity/Category.java
  src/main/java/com/spare4fun/core/entity/Item.java
  src/main/java/com/spare4fun/core/entity/ItemCondition.java
  src/main/java/com/spare4fun/core/entity/Location.java
  src/main/java/com/spare4fun/core/entity/Offer.java
  src/main/java/com/spare4fun/core/entity/PaymentOrder.java
  src/main/java/com/spare4fun/core/entity/README.md
  src/main/java/com/spare4fun/core/entity/SavedItemsCart.java
  src/main/java/com/spare4fun/core/entity/TimeSlot.java
  src/main/java/com/spare4fun/core/entity/User.java
  src/main/java/com/spare4fun/core/entity/UserInfo.java
Labels: enhancement, help wanted

#21 Entity p2 merge to Main (some changes were made)
  src/main/java/com/spare4fun/core/entity/Appointment.java
  src/main/java/com/spare4fun/core/entity/Item.java
  src/main/java/com/spare4fun/core/entity/Offer.java
Labels: bug

#27 Feature user 1 sign up
  pom.xml
  src/main/java/com/spare4fun/core/ConverterConfig.java
  src/main/java/com/spare4fun/core/controller/RegistrationController.java
  src/main/java/com/spare4fun/core/dao/UserDao.java
  src/main/java/com/spare4fun/core/dao/UserDaoImpl.java
  src/main/java/com/spare4fun/core/dto/MessageDto.java
  src/main/java/com/spare4fun/core/dto/UserDto.java
  src/main/java/com/spare4fun/core/entity/Appointment.java
  src/main/java/com/spare4fun/core/entity/Authorities.java
  src/main/java/com/spare4fun/core/entity/Category.java
  src/main/java/com/spare4fun/core/entity/Item.java
  src/main/java/com/spare4fun/core/entity/ItemCondition.java
  src/main/java/com/spare4fun/core/entity/Location.java
  src/main/java/com/spare4fun/core/entity/Offer.java
  src/main/java/com/spare4fun/core/entity/PaymentOrder.java
  src/main/java/com/spare4fun/core/entity/Role.java
  src/main/java/com/spare4fun/core/entity/SavedItemsCart.java
  src/main/java/com/spare4fun/core/entity/TimeSlot.java
  src/main/java/com/spare4fun/core/entity/User.java
  src/main/java/com/spare4fun/core/entity/UserInfo.java
  src/main/java/com/spare4fun/core/exception/DuplicateUserException.java
  src/main/java/com/spare4fun/core/security/ApplicationSecurityConfig.java
  src/main/java/com/spare4fun/core/security/PasswordConfig.java
  src/main/java/com/spare4fun/core/service/UserAuthService.java
  src/main/java/com/spare4fun/core/service/UserService.java
  src/test/java/com/spare4fun/core/CoreApplicationTests.java
  src/test/java/com/spare4fun/core/test/controller/RegistrationControllerTest.java
  src/test/java/com/spare4fun/core/test/dao/UserDaoTest.java
  src/test/java/com/spare4fun/core/test/service/README.md
Labels: enhancement, help wanted

#23 Set Up Spring Security
  pom.xml
  src/main/java/com/spare4fun/core/dao/UserDao.java
  src/main/java/com/spare4fun/core/dao/UserDaoImpl.java
  src/main/java/com/spare4fun/core/dto/README.md
  src/main/java/com/spare4fun/core/entity/Authorities.java
  src/main/java/com/spare4fun/core/entity/Role.java
  src/main/java/com/spare4fun/core/entity/User.java
  src/main/java/com/spare4fun/core/exception/DuplicateUserException.java
  src/main/java/com/spare4fun/core/exception/README.md
  src/main/java/com/spare4fun/core/security/ApplicationSecurityConfig.java
  src/main/java/com/spare4fun/core/security/PasswordConfig.java
  src/main/java/com/spare4fun/core/security/README.md
  src/main/java/com/spare4fun/core/service/UserAuthService.java
  src/test/java/com/spare4fun/core/CoreApplicationTests.java
  src/test/java/com/spare4fun/core/test/controller/README.md
  src/test/java/com/spare4fun/core/test/dao/README.md
  src/test/java/com/spare4fun/core/test/dao/UserDaoTest.java
Labels: enhancement, help wanted

#29 Feature user 2 login
  pom.xml
  src/main/java/com/spare4fun/core/dao/UserDao.java
  src/main/java/com/spare4fun/core/dao/UserDaoImpl.java
  src/main/java/com/spare4fun/core/dto/UserDto.java
  src/main/java/com/spare4fun/core/security/ApplicationSecurityConfig.java
  src/main/java/com/spare4fun/core/service/UserAuthService.java
  src/test/java/com/spare4fun/core/test/dao/UserDaoTest.java
Labels: enhancement

#28 Database V2.0 merge to master branch
  pom.xml
  src/main/java/com/spare4fun/core/dao/UserDao.java
  src/main/java/com/spare4fun/core/dao/UserDaoImpl.java
  src/main/java/com/spare4fun/core/entity/Appointment.java
  src/main/java/com/spare4fun/core/entity/Authorities.java
  src/main/java/com/spare4fun/core/entity/Category.java
  src/main/java/com/spare4fun/core/entity/Item.java
  src/main/java/com/spare4fun/core/entity/ItemCondition.java
  src/main/java/com/spare4fun/core/entity/Location.java
  src/main/java/com/spare4fun/core/entity/Offer.java
  src/main/java/com/spare4fun/core/entity/PaymentOrder.java
  src/main/java/com/spare4fun/core/entity/Role.java
  src/main/java/com/spare4fun/core/entity/SavedItemsCart.java
  src/main/java/com/spare4fun/core/entity/TimeSlot.java
  src/main/java/com/spare4fun/core/entity/User.java
  src/main/java/com/spare4fun/core/entity/UserInfo.java
  src/main/java/com/spare4fun/core/exception/DuplicateUserException.java
  src/main/java/com/spare4fun/core/security/ApplicationSecurityConfig.java
  src/main/java/com/spare4fun/core/security/PasswordConfig.java
  src/main/java/com/spare4fun/core/service/UserAuthService.java
  src/test/java/com/spare4fun/core/CoreApplicationTests.java
  src/test/java/com/spare4fun/core/test/dao/UserDaoTest.java
Labels: enhancement, help wanted

#32 Bug fixed issue #30 (from database, merge to main)
  src/main/java/com/spare4fun/core/dao/UserDaoImpl.java
Labels: bug
