Repository flag-camp-2020-t3/Spare4Fun-Server, pull requests merged in 2020-12, with the labels that each got.

#33 buyer feature 35 & 37
  .gitignore
  core.iml
  pom.xml
  src/main/java/com/spare4fun/core/controller/OfferController.java
  src/main/java/com/spare4fun/core/dao/ItemDao.java
  src/main/java/com/spare4fun/core/dao/ItemDaoImpl.java
  src/main/java/com/spare4fun/core/dao/OfferDao.java
  src/main/java/com/spare4fun/core/dao/OfferDaoImpl.java
  src/main/java/com/spare4fun/core/dao/UserDao.java
  src/main/java/com/spare4fun/core/dao/UserDaoImpl.java
  src/main/java/com/spare4fun/core/dto/OfferDto.java
  src/main/java/com/spare4fun/core/entity/Appointment.java
  src/main/java/com/spare4fun/core/entity/Authorities.java
  src/main/java/com/spare4fun/core/entity/Category.java
  src/main/java/com/spare4fun/core/entity/Item.java
  src/main/java/com/spare4fun/core/entity/ItemCondition.java
  src/main/java/com/spare4fun/core/entity/Location.java
  src/main/java/com/spare4fun/core/entity/Offer.java
  src/main/java/com/spare4fun/core/entity/PaymentOrder.java
  src/main/java/com/spare4fun/core/entity/Role.java
  src/main/java/com/spare4fun/core/entity/SavedItemsCart.java
  src/main/java/com/spare4fun/core/entity/TimeSlot.java
  src/main/java/com/spare4fun/core/entity/User.java
  src/main/java/com/spare4fun/core/entity/UserInfo.java
  src/main/java/com/spare4fun/core/exception/DuplicateUserException.java
  src/main/java/com/spare4fun/core/exception/README.md
  src/main/java/com/spare4fun/core/security/ApplicationSecurityConfig.java
  src/main/java/com/spare4fun/core/security/PasswordConfig.java
  src/main/java/com/spare4fun/core/service/ItemService.java
  src/main/java/com/spare4fun/core/service/OfferService.java
  src/main/java/com/spare4fun/core/service/UserAuthService.java
  src/test/java/com/spare4fun/core/CoreApplicationTests.java
  src/test/java/com/spare4fun/core/test/dao/OfferDaoTest.java
  src/test/java/com/spare4fun/core/test/dao/UserDaoTest.java
  src/test/java/com/spare4fun/core/test/service/OfferServiceTest.java
Labels: enhancement

#35 set some columns nullable
  src/main/java/com/spare4fun/core/entity/Appointment.java
  src/main/java/com/spare4fun/core/entity/Item.java
  src/main/java/com/spare4fun/core/entity/Offer.java
  src/main/java/com/spare4fun/core/entity/SavedItemsCart.java
  src/main/java/com/spare4fun/core/entity/TimeSlot.java
  src/main/java/com/spare4fun/core/entity/User.java
  src/main/java/com/spare4fun/core/entity/UserInfo.java
Labels: enhancement

#36 Feature buyer s1
  pom.xml
  src/main/java/com/spare4fun/core/controller/OfferController.java
  src/main/java/com/spare4fun/core/dao/ItemDao.java
  src/main/java/com/spare4fun/core/dao/ItemDaoImpl.java
  src/main/java/com/spare4fun/core/dao/LocationDao.java
  src/main/java/com/spare4fun/core/dao/LocationDaoImpl.java
  src/main/java/com/spare4fun/core/dao/OfferDao.java
  src/main/java/com/spare4fun/core/dao/OfferDaoImpl.java
  src/main/java/com/spare4fun/core/dto/OfferDto.java
  src/main/java/com/spare4fun/core/service/ItemService.java
  src/main/java/com/spare4fun/core/service/OfferService.java
  src/test/java/com/spare4fun/core/test/dao/OfferDaoTest.java
  src/test/java/com/spare4fun/core/test/service/OfferServiceTest.java
Labels: enhancement

#39 OfferServiceTest work with modifed saved items association
  src/test/java/com/spare4fun/core/test/dao/OfferDaoTest.java
  src/test/java/com/spare4fun/core/test/service/OfferServiceTest.java
Labels: bug, help wanted

#41 bug fixed #40
  src/main/java/com/spare4fun/core/controller/RegistrationController.java
  src/test/java/com/spare4fun/core/test/controller/RegistrationControllerTest.java
Labels: bug

#42 Feature seller 25 get items by user
  pom.xml
  src/main/java/com/spare4fun/core/ConverterConfig.java
  src/main/java/com/spare4fun/core/controller/OfferController.java
  src/main/java/com/spare4fun/core/controller/RegistrationController.java
  src/main/java/com/spare4fun/core/controller/SellerController.java
  src/main/java/com/spare4fun/core/dao/ItemDao.java
  src/main/java/com/spare4fun/core/dao/ItemDaoImpl.java
  src/main/java/com/spare4fun/core/dao/LocationDao.java
  src/main/java/com/spare4fun/core/dao/LocationDaoImpl.java
  src/main/java/com/spare4fun/core/dao/OfferDao.java
  src/main/java/com/spare4fun/core/dao/OfferDaoImpl.java
  src/main/java/com/spare4fun/core/dao/UserDao.java
  src/main/java/com/spare4fun/core/dao/UserDaoImpl.java
  src/main/java/com/spare4fun/core/dto/ItemDto.java
  src/main/java/com/spare4fun/core/dto/LocationDto.java
  src/main/java/com/spare4fun/core/dto/MessageDto.java
  src/main/java/com/spare4fun/core/dto/OfferDto.java
  src/main/java/com/spare4fun/core/dto/UserDto.java
  src/main/java/com/spare4fun/core/entity/Appointment.java
  src/main/java/com/spare4fun/core/entity/Item.java
  src/main/java/com/spare4fun/core/entity/Offer.java
  src/main/java/com/spare4fun/core/entity/SavedItemsCart.java
  src/main/java/com/spare4fun/core/entity/TimeSlot.java
  src/main/java/com/spare4fun/core/entity/User.java
  src/main/java/com/spare4fun/core/entity/UserInfo.java
  src/main/java/com/spare4fun/core/security/ApplicationSecurityConfig.java
  src/main/java/com/spare4fun/core/service/ItemService.java
  src/main/java/com/spare4fun/core/service/LocationService.java
  src/main/java/com/spare4fun/core/service/OfferService.java
  src/main/java/com/spare4fun/core/service/UserAuthService.java
  src/main/java/com/spare4fun/core/service/UserService.java
  src/test/java/com/spare4fun/core/test/controller/RegistrationControllerTest.java
  src/test/java/com/spare4fun/core/test/controller/SellerControllerTest.java
  src/test/java/com/spare4fun/core/test/dao/OfferDaoTest.java
  src/test/java/com/spare4fun/core/test/dao/UserDaoTest.java
  src/test/java/com/spare4fun/core/test/service/OfferServiceTest.java
  src/test/java/com/spare4fun/core/test/service/README.md
Labels: enhancement

#51 set availTime nullable
  src/main/java/com/spare4fun/core/entity/Appointment.java
Labels: bug

#58 changes made in LocationService related to issue #57
  pom.xml
  src/main/java/com/spare4fun/core/ConverterConfig.java
  src/main/java/com/spare4fun/core/controller/ItemController.java
  src/main/java/com/spare4fun/core/controller/OfferController.java
  src/main/java/com/spare4fun/core/dto/OfferDto.java
  src/main/java/com/spare4fun/core/service/LocationService.java
  src/test/java/com/spare4fun/core/test/controller/ItemControllerTest.java
Labels: enhancement

#60 Wrapper class in entity for ModelMapper
  src/main/java/com/spare4fun/core/entity/Item.java
  src/main/java/com/spare4fun/core/entity/Offer.java
  src/main/java/com/spare4fun/core/entity/PaymentOrder.java
Labels: enhancement

#61 Update Item.java [addition to #59 #60]
  src/main/java/com/spare4fun/core/entity/Item.java
Labels: bug

#63 Revert "Wrapper class in entity for ModelMapper"
  src/main/java/com/spare4fun/core/entity/Item.java
  src/main/java/com/spare4fun/core/entity/Offer.java
  src/main/java/com/spare4fun/core/entity/PaymentOrder.java
Labels: bug

#68 Extended Database Dao #46
  src/main/java/com/spare4fun/core/dao/CategoryDao.java
  src/main/java/com/spare4fun/core/dao/CategoryDaoImpl.java
  src/main/java/com/spare4fun/core/dao/ItemConditionDao.java
  src/main/java/com/spare4fun/core/dao/ItemConditionDaoImpl.java
  src/main/java/com/spare4fun/core/dao/ItemDao.java
  src/main/java/com/spare4fun/core/dao/ItemDaoImpl.java
  src/main/java/com/spare4fun/core/dao/LocationDaoImpl.java
  src/main/java/com/spare4fun/core/dao/OfferDaoImpl.java
  src/main/java/com/spare4fun/core/dao/PaymentOrderDao.java
  src/main/java/com/spare4fun/core/dao/UserDaoImpl.java
  src/main/java/com/spare4fun/core/exception/DuplicateCategoryException.java
  src/main/java/com/spare4fun/core/exception/DuplicateItemConditionException.java
  src/test/java/com/spare4fun/core/test/dao/CategoryDaoTest.java
  src/test/java/com/spare4fun/core/test/dao/ItemConditionDaoTest.java
Labels: enhancement

#71 Feature seller 24
  pom.xml
  src/main/java/com/spare4fun/core/ConverterConfig.java
  src/main/java/com/spare4fun/core/controller/ItemController.java
  src/main/java/com/spare4fun/core/controller/OfferController.java
  src/main/java/com/spare4fun/core/dao/CategoryDao.java
  src/main/java/com/spare4fun/core/dao/CategoryDaoImpl.java
  src/main/java/com/spare4fun/core/dao/ItemConditionDao.java
  src/main/java/com/spare4fun/core/dao/ItemConditionDaoImpl.java
  src/main/java/com/spare4fun/core/dao/ItemDao.java
  src/main/java/com/spare4fun/core/dao/ItemDaoImpl.java
  src/main/java/com/spare4fun/core/dao/LocationDaoImpl.java
  src/main/java/com/spare4fun/core/dao/OfferDaoImpl.java
  src/main/java/com/spare4fun/core/dao/PaymentOrderDao.java
  src/main/java/com/spare4fun/core/dao/UserDaoImpl.java
  src/main/java/com/spare4fun/core/dto/OfferDto.java
  src/main/java/com/spare4fun/core/exception/DuplicateCategoryException.java
  src/main/java/com/spare4fun/core/exception/DuplicateItemConditionException.java
  src/main/java/com/spare4fun/core/exception/InvalidPriceException.java
  src/main/java/com/spare4fun/core/exception/InvalidQuantityException.java
  src/main/java/com/spare4fun/core/exception/ItemNotFoundException.java
  src/main/java/com/spare4fun/core/service/ItemService.java
  src/main/java/com/spare4fun/core/service/LocationService.java
  src/main/java/com/spare4fun/core/service/OfferService.java
  src/test/java/com/spare4fun/core/test/controller/ItemControllerTest.java
  src/test/java/com/spare4fun/core/test/dao/CategoryDaoTest.java
  src/test/java/com/spare4fun/core/test/dao/ItemConditionDaoTest.java
  src/test/java/com/spare4fun/core/test/dao/ItemDaoTest.java
  src/test/java/com/spare4fun/core/test/dao/OfferDaoTest.java
  src/test/java/com/spare4fun/core/test/service/ItemServiceTest.java
  src/test/java/com/spare4fun/core/test/service/OfferServiceTest.java
Labels: enhancement

#72 Feature seller s1
  src/main/java/com/spare4fun/core/controller/ItemController.java
  src/main/java/com/spare4fun/core/exception/InvalidPriceException.java
  src/main/java/com/spare4fun/core/exception/InvalidQuantityException.java
  src/main/java/com/spare4fun/core/exception/ItemNotFoundException.java
  src/main/java/com/spare4fun/core/service/ItemService.java
  src/main/java/com/spare4fun/core/service/LocationService.java
  src/test/java/com/spare4fun/core/test/controller/ItemControllerTest.java
  src/test/java/com/spare4fun/core/test/service/ItemServiceTest.java
  src/test/java/com/spare4fun/core/test/service/OfferServiceTest.java
Labels: enhancement

#70 Modified ApplicationSecurityConfig & Cross-Origin Setting
  src/main/java/com/spare4fun/core/CoreApplication.java
  src/main/java/com/spare4fun/core/security/ApplicationSecurityConfig.java
Labels: enhancement

#73 [Feature user s1] added cross-origin & login handler
  src/main/java/com/spare4fun/core/CoreApplication.java
  src/main/java/com/spare4fun/core/security/ApplicationSecurityConfig.java
Labels: enhancement

#78 update message returned back for username
  src/main/java/com/spare4fun/core/ConverterConfig.java
  src/main/java/com/spare4fun/core/security/ApplicationSecurityConfig.java
Labels: v1.0

#81 #80 removed offer's Cascade.ALL in Appointment entity
  src/main/java/com/spare4fun/core/entity/Appointment.java
  src/test/java/com/spare4fun/core/test/dao/AppointmentDaoTest.java
  src/test/java/com/spare4fun/core/test/dao/TimeSlotDaoTest.java
Labels: bug, buyer, db-v3.0

#84 Secret.java is deprecated
  src/main/java/com/spare4fun/core/HibernateConfig.java
  src/main/resources/application.properties
Labels: backend-v2.0, documentation, enhancement

#93 Quick Fix of MultipleBagFetchException
  src/main/java/com/spare4fun/core/entity/Location.java
Labels: bug, db-v3.0
